version: "2.2"

services:
  track-me:
    # custom dockerfile
    build: .
    container_name: track-me
    volumes:
      - ${PWD}/certs/:/app/certs
      - ${PWD}/config.json:/app/config.json
      - ${PWD}/blockedIPs:/app/blockedIPs
    depends_on:
      - mongo
    ports:
      - "8443:443"
      - "8080:80"
    
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ${PWD}/mongo:/data/db
    ports:
      - "27017:27017"